Vagrant.configure("2") do |config|
    config.vm.box = "mcandre/vagrant-debian-cpp-ppc64el"

    # config.vm.provider :libvirt do |v, override|
    #     v.uri = 'qemu+unix:///system'
    #     # v.host = "server"
    #     # v.username = "vagrant"
    #     # v.connect_via_ssh = true
    #     # v.management_network_name = "vagrant-libvirt-new"
    #     # v.management_network_address = "192.168.124.0/24"
    #     # override.ssh.proxy_command = "ssh server -l vagrant nc -N %h %p"
    # end
end
